name: Run BHRC Blockchain Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Reposyu klonla
        uses: actions/checkout@v3

      - name: Python 3.10 kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Bağımlılıkları kur
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Pytest + Coverage çalıştır
        run: |
          pytest --cov=bhrc_blockchain --cov-report=term-missing

