name: Run Pytest with Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Checkout Et
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Bağımlılıkları Kur
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Testleri Çalıştır
        run: |
          pytest --cov=./ --cov-report=term-missing

