name: Run BHRC Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu çek
      uses: actions/checkout@v3

    - name: Python ortamı kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Tüm testleri çalıştır ve coverage al
      run: |
        export PYTHONPATH=./bhrc_blockchain
        chmod +x run_all_tests.sh
        ./run_all_tests.sh

    - name: HTML coverage çıktısını sakla (isteğe bağlı)
      uses: actions/upload-artifact@v4
      with:
        name: htmlcov
        path: htmlcov/

